import { Video, RentfrowDimension, SessionSummary, TextCard } from "./supabase/types";

// Demo video corpus — real YouTube video IDs across the 5 Rentfrow dimensions
// Each dimension has ~12 videos for the demo (60 in full version)

export const DIMENSION_LABELS: Record<
  RentfrowDimension,
  { label: string; description: string; color: string }
> = {
  communal: {
    label: "Communal",
    description: "Warmth, social bonding, romance, family",
    color: "#f59e0b",
  },
  aesthetic: {
    label: "Aesthetic",
    description: "Beauty, art, complexity, reflection",
    color: "#8b5cf6",
  },
  dark: {
    label: "Dark",
    description: "Horror, thriller, edgy, transgressive",
    color: "#ef4444",
  },
  thrilling: {
    label: "Thrilling",
    description: "Action, adventure, risk, spectacle",
    color: "#06b6d4",
  },
  cerebral: {
    label: "Cerebral",
    description: "Documentary, science, informational",
    color: "#22c55e",
  },
};

export const DEMO_VIDEOS: Video[] = [
  // ===== COMMUNAL =====
  {
    id: "c001",
    youtube_id: "dQw4w9WgXcQ",
    title: "Classic Feel-Good Music",
    duration_seconds: 212,
    dim_communal: 0.9,
    dim_aesthetic: 0.2,
    dim_dark: 0.0,
    dim_thrilling: 0.1,
    dim_cerebral: 0.0,
    attr_pace: "medium",
    attr_valence: "warm",
    attr_complexity: "simple",
    attr_social_density: "solo",
    attr_novelty: "familiar",
    attr_production: "polished",
    diag_openness: 0.3,
    diag_conscientiousness: 0.4,
    diag_extraversion: 0.6,
    diag_agreeableness: 0.7,
    diag_neuroticism: 0.3,
    added_at: new Date().toISOString(),
  },
  {
    id: "c002",
    youtube_id: "ZbZSe6N_BXs",
    title: "Happy Together - Heartwarming",
    duration_seconds: 178,
    dim_communal: 0.95,
    dim_aesthetic: 0.1,
    dim_dark: 0.0,
    dim_thrilling: 0.05,
    dim_cerebral: 0.0,
    attr_pace: "medium",
    attr_valence: "warm",
    attr_complexity: "simple",
    attr_social_density: "small_group",
    attr_novelty: "familiar",
    attr_production: "polished",
    diag_openness: 0.3,
    diag_conscientiousness: 0.5,
    diag_extraversion: 0.7,
    diag_agreeableness: 0.8,
    diag_neuroticism: 0.2,
    added_at: new Date().toISOString(),
  },
  {
    id: "c003",
    youtube_id: "450p7goxZqg",
    title: "Family Cooking Together",
    duration_seconds: 240,
    dim_communal: 0.85,
    dim_aesthetic: 0.3,
    dim_dark: 0.0,
    dim_thrilling: 0.0,
    dim_cerebral: 0.1,
    attr_pace: "slow",
    attr_valence: "warm",
    attr_complexity: "simple",
    attr_social_density: "small_group",
    attr_novelty: "familiar",
    attr_production: "moderate",
    diag_openness: 0.4,
    diag_conscientiousness: 0.6,
    diag_extraversion: 0.5,
    diag_agreeableness: 0.8,
    diag_neuroticism: 0.2,
    added_at: new Date().toISOString(),
  },
  {
    id: "c004",
    youtube_id: "Bag1gUxuU0g",
    title: "Wholesome Pet Rescue Compilation",
    duration_seconds: 300,
    dim_communal: 0.9,
    dim_aesthetic: 0.1,
    dim_dark: 0.0,
    dim_thrilling: 0.2,
    dim_cerebral: 0.0,
    attr_pace: "medium",
    attr_valence: "warm",
    attr_complexity: "simple",
    attr_social_density: "small_group",
    attr_novelty: "moderate",
    attr_production: "raw",
    diag_openness: 0.4,
    diag_conscientiousness: 0.5,
    diag_extraversion: 0.5,
    diag_agreeableness: 0.9,
    diag_neuroticism: 0.3,
    added_at: new Date().toISOString(),
  },

  // ===== AESTHETIC =====
  {
    id: "a001",
    youtube_id: "36YnV9STBqc",
    title: "Breathtaking Cinematography Reel",
    duration_seconds: 195,
    dim_communal: 0.1,
    dim_aesthetic: 0.95,
    dim_dark: 0.1,
    dim_thrilling: 0.2,
    dim_cerebral: 0.2,
    attr_pace: "slow",
    attr_valence: "neutral",
    attr_complexity: "complex",
    attr_social_density: "solo",
    attr_novelty: "moderate",
    attr_production: "polished",
    diag_openness: 0.9,
    diag_conscientiousness: 0.4,
    diag_extraversion: 0.3,
    diag_agreeableness: 0.5,
    diag_neuroticism: 0.5,
    added_at: new Date().toISOString(),
  },
  {
    id: "a002",
    youtube_id: "v2kV6pgJxuo",
    title: "Japanese Pottery Master at Work",
    duration_seconds: 420,
    dim_communal: 0.1,
    dim_aesthetic: 0.9,
    dim_dark: 0.0,
    dim_thrilling: 0.0,
    dim_cerebral: 0.3,
    attr_pace: "slow",
    attr_valence: "warm",
    attr_complexity: "moderate",
    attr_social_density: "solo",
    attr_novelty: "moderate",
    attr_production: "polished",
    diag_openness: 0.85,
    diag_conscientiousness: 0.6,
    diag_extraversion: 0.2,
    diag_agreeableness: 0.5,
    diag_neuroticism: 0.4,
    added_at: new Date().toISOString(),
  },
  {
    id: "a003",
    youtube_id: "hHW1oY26kxQ",
    title: "Nature Macro Photography",
    duration_seconds: 300,
    dim_communal: 0.0,
    dim_aesthetic: 0.9,
    dim_dark: 0.05,
    dim_thrilling: 0.1,
    dim_cerebral: 0.2,
    attr_pace: "slow",
    attr_valence: "neutral",
    attr_complexity: "moderate",
    attr_social_density: "solo",
    attr_novelty: "strange",
    attr_production: "polished",
    diag_openness: 0.9,
    diag_conscientiousness: 0.3,
    diag_extraversion: 0.2,
    diag_agreeableness: 0.4,
    diag_neuroticism: 0.5,
    added_at: new Date().toISOString(),
  },
  {
    id: "a004",
    youtube_id: "qASgtA7mlPU",
    title: "Abstract Art Creation Process",
    duration_seconds: 360,
    dim_communal: 0.0,
    dim_aesthetic: 0.95,
    dim_dark: 0.2,
    dim_thrilling: 0.0,
    dim_cerebral: 0.3,
    attr_pace: "slow",
    attr_valence: "neutral",
    attr_complexity: "complex",
    attr_social_density: "solo",
    attr_novelty: "strange",
    attr_production: "moderate",
    diag_openness: 0.95,
    diag_conscientiousness: 0.3,
    diag_extraversion: 0.2,
    diag_agreeableness: 0.4,
    diag_neuroticism: 0.6,
    added_at: new Date().toISOString(),
  },

  // ===== DARK =====
  {
    id: "d001",
    youtube_id: "DUMq6imrMmI",
    title: "Unsettling Short Film",
    duration_seconds: 480,
    dim_communal: 0.0,
    dim_aesthetic: 0.3,
    dim_dark: 0.95,
    dim_thrilling: 0.3,
    dim_cerebral: 0.2,
    attr_pace: "slow",
    attr_valence: "dark",
    attr_complexity: "complex",
    attr_social_density: "solo",
    attr_novelty: "strange",
    attr_production: "polished",
    diag_openness: 0.8,
    diag_conscientiousness: 0.3,
    diag_extraversion: 0.3,
    diag_agreeableness: 0.2,
    diag_neuroticism: 0.7,
    added_at: new Date().toISOString(),
  },
  {
    id: "d002",
    youtube_id: "Dw4oet5f0uI",
    title: "Urban Exploration - Abandoned Places",
    duration_seconds: 600,
    dim_communal: 0.0,
    dim_aesthetic: 0.4,
    dim_dark: 0.8,
    dim_thrilling: 0.4,
    dim_cerebral: 0.2,
    attr_pace: "medium",
    attr_valence: "dark",
    attr_complexity: "moderate",
    attr_social_density: "solo",
    attr_novelty: "strange",
    attr_production: "raw",
    diag_openness: 0.7,
    diag_conscientiousness: 0.3,
    diag_extraversion: 0.4,
    diag_agreeableness: 0.3,
    diag_neuroticism: 0.6,
    added_at: new Date().toISOString(),
  },
  {
    id: "d003",
    youtube_id: "FNXwKGZHmDc",
    title: "Dark Comedy Compilation",
    duration_seconds: 360,
    dim_communal: 0.1,
    dim_aesthetic: 0.1,
    dim_dark: 0.85,
    dim_thrilling: 0.1,
    dim_cerebral: 0.3,
    attr_pace: "fast",
    attr_valence: "dark",
    attr_complexity: "moderate",
    attr_social_density: "small_group",
    attr_novelty: "moderate",
    attr_production: "moderate",
    diag_openness: 0.7,
    diag_conscientiousness: 0.3,
    diag_extraversion: 0.5,
    diag_agreeableness: 0.2,
    diag_neuroticism: 0.5,
    added_at: new Date().toISOString(),
  },
  {
    id: "d004",
    youtube_id: "HjGkB_oWTe0",
    title: "Dystopian Sci-Fi Short",
    duration_seconds: 540,
    dim_communal: 0.0,
    dim_aesthetic: 0.5,
    dim_dark: 0.9,
    dim_thrilling: 0.3,
    dim_cerebral: 0.4,
    attr_pace: "medium",
    attr_valence: "dark",
    attr_complexity: "complex",
    attr_social_density: "solo",
    attr_novelty: "strange",
    attr_production: "polished",
    diag_openness: 0.85,
    diag_conscientiousness: 0.3,
    diag_extraversion: 0.3,
    diag_agreeableness: 0.2,
    diag_neuroticism: 0.7,
    added_at: new Date().toISOString(),
  },

  // ===== THRILLING =====
  {
    id: "t001",
    youtube_id: "GDhBwHsc1ag",
    title: "Extreme Freesoloing POV",
    duration_seconds: 300,
    dim_communal: 0.0,
    dim_aesthetic: 0.3,
    dim_dark: 0.2,
    dim_thrilling: 0.95,
    dim_cerebral: 0.0,
    attr_pace: "fast",
    attr_valence: "neutral",
    attr_complexity: "simple",
    attr_social_density: "solo",
    attr_novelty: "strange",
    attr_production: "raw",
    diag_openness: 0.6,
    diag_conscientiousness: 0.3,
    diag_extraversion: 0.8,
    diag_agreeableness: 0.3,
    diag_neuroticism: 0.4,
    added_at: new Date().toISOString(),
  },
  {
    id: "t002",
    youtube_id: "nLwML2PagbY",
    title: "Storm Chasing Close Call",
    duration_seconds: 420,
    dim_communal: 0.0,
    dim_aesthetic: 0.4,
    dim_dark: 0.3,
    dim_thrilling: 0.9,
    dim_cerebral: 0.2,
    attr_pace: "fast",
    attr_valence: "neutral",
    attr_complexity: "moderate",
    attr_social_density: "small_group",
    attr_novelty: "moderate",
    attr_production: "raw",
    diag_openness: 0.6,
    diag_conscientiousness: 0.2,
    diag_extraversion: 0.7,
    diag_agreeableness: 0.3,
    diag_neuroticism: 0.5,
    added_at: new Date().toISOString(),
  },
  {
    id: "t003",
    youtube_id: "bpyX5E1tARk",
    title: "Parkour Through the City",
    duration_seconds: 240,
    dim_communal: 0.1,
    dim_aesthetic: 0.3,
    dim_dark: 0.1,
    dim_thrilling: 0.9,
    dim_cerebral: 0.0,
    attr_pace: "fast",
    attr_valence: "neutral",
    attr_complexity: "simple",
    attr_social_density: "solo",
    attr_novelty: "moderate",
    attr_production: "moderate",
    diag_openness: 0.5,
    diag_conscientiousness: 0.3,
    diag_extraversion: 0.8,
    diag_agreeableness: 0.4,
    diag_neuroticism: 0.3,
    added_at: new Date().toISOString(),
  },
  {
    id: "t004",
    youtube_id: "kk5JkhGwMOo",
    title: "Space Launch Compilation",
    duration_seconds: 360,
    dim_communal: 0.2,
    dim_aesthetic: 0.5,
    dim_dark: 0.0,
    dim_thrilling: 0.85,
    dim_cerebral: 0.4,
    attr_pace: "medium",
    attr_valence: "warm",
    attr_complexity: "moderate",
    attr_social_density: "crowd",
    attr_novelty: "moderate",
    attr_production: "polished",
    diag_openness: 0.7,
    diag_conscientiousness: 0.5,
    diag_extraversion: 0.5,
    diag_agreeableness: 0.5,
    diag_neuroticism: 0.3,
    added_at: new Date().toISOString(),
  },

  // ===== CEREBRAL =====
  {
    id: "e001",
    youtube_id: "aircAruvnKk",
    title: "Math Visualization - Fractals",
    duration_seconds: 480,
    dim_communal: 0.0,
    dim_aesthetic: 0.5,
    dim_dark: 0.0,
    dim_thrilling: 0.1,
    dim_cerebral: 0.95,
    attr_pace: "slow",
    attr_valence: "neutral",
    attr_complexity: "complex",
    attr_social_density: "solo",
    attr_novelty: "strange",
    attr_production: "polished",
    diag_openness: 0.9,
    diag_conscientiousness: 0.7,
    diag_extraversion: 0.2,
    diag_agreeableness: 0.4,
    diag_neuroticism: 0.4,
    added_at: new Date().toISOString(),
  },
  {
    id: "e002",
    youtube_id: "rHp3DlLLCR4",
    title: "Engineering Marvels Explained",
    duration_seconds: 600,
    dim_communal: 0.0,
    dim_aesthetic: 0.2,
    dim_dark: 0.0,
    dim_thrilling: 0.2,
    dim_cerebral: 0.9,
    attr_pace: "medium",
    attr_valence: "neutral",
    attr_complexity: "complex",
    attr_social_density: "solo",
    attr_novelty: "moderate",
    attr_production: "polished",
    diag_openness: 0.8,
    diag_conscientiousness: 0.7,
    diag_extraversion: 0.3,
    diag_agreeableness: 0.5,
    diag_neuroticism: 0.3,
    added_at: new Date().toISOString(),
  },
  {
    id: "e003",
    youtube_id: "WFoC3TR5rzI",
    title: "Philosophy of Consciousness",
    duration_seconds: 540,
    dim_communal: 0.1,
    dim_aesthetic: 0.3,
    dim_dark: 0.2,
    dim_thrilling: 0.0,
    dim_cerebral: 0.9,
    attr_pace: "slow",
    attr_valence: "neutral",
    attr_complexity: "complex",
    attr_social_density: "solo",
    attr_novelty: "moderate",
    attr_production: "moderate",
    diag_openness: 0.95,
    diag_conscientiousness: 0.5,
    diag_extraversion: 0.2,
    diag_agreeableness: 0.4,
    diag_neuroticism: 0.6,
    added_at: new Date().toISOString(),
  },
  {
    id: "e004",
    youtube_id: "iG9CE55wbtY",
    title: "History of Cryptography",
    duration_seconds: 480,
    dim_communal: 0.0,
    dim_aesthetic: 0.1,
    dim_dark: 0.1,
    dim_thrilling: 0.2,
    dim_cerebral: 0.9,
    attr_pace: "medium",
    attr_valence: "neutral",
    attr_complexity: "complex",
    attr_social_density: "solo",
    attr_novelty: "moderate",
    attr_production: "polished",
    diag_openness: 0.8,
    diag_conscientiousness: 0.7,
    diag_extraversion: 0.3,
    diag_agreeableness: 0.4,
    diag_neuroticism: 0.3,
    added_at: new Date().toISOString(),
  },
];

// Helper: get videos by primary dimension
export function getVideosByDimension(dim: RentfrowDimension): Video[] {
  const key = `dim_${dim}` as keyof Video;
  return DEMO_VIDEOS.filter((v) => (v[key] as number) >= 0.6).sort(
    (a, b) => (b[key] as number) - (a[key] as number)
  );
}

// System default queue order (Section 6)
export function getSystemDefaultQueue(): Video[] {
  const dims: RentfrowDimension[] = [
    "cerebral",
    "thrilling",
    "aesthetic",
    "communal",
    "dark",
    "cerebral",
    "aesthetic",
    "thrilling",
    "communal",
    "dark",
  ];
  return dims.map((dim) => {
    const pool = getVideosByDimension(dim);
    return pool[Math.floor(Math.random() * pool.length)];
  });
}

// Demo session summary for the reveal sequence
export const DEMO_SESSION_SUMMARY: SessionSummary = {
  id: "demo-summary",
  session_id: "demo-session",
  duration_seconds: 863,
  total_videos_shown: 22,
  optimizer_videos_shown: 14,
  system_videos_shown: 8,
  avg_dwell_optimizer_ms: 8200,
  avg_dwell_system_ms: 5100,
  engagement_multiplier: 1.61,
  total_info_gain: 4.32,
  dimensions_explored: 4,
  exploration_entropy: 1.42,
  optimizer_score: 1174,
  final_feature_vector: {
    communal: 0.72,
    aesthetic: 0.85,
    dark: 0.35,
    thrilling: 0.48,
    cerebral: 0.68,
  },
  final_umap_coords: { x: 0.62, y: 0.38 },
  scroller_accepted_call: null,
  optimizer_accepted_call: null,
  call_duration_seconds: null,
  created_at: new Date().toISOString(),
};

// Demo text cards for reveal replay
export const DEMO_TEXT_CARDS: TextCard[] = [
  {
    id: "tc1",
    session_id: "demo-session",
    content: "We noticed you paused on that one.",
    sent_at_ms: 45000,
    sent_at: new Date().toISOString(),
  },
  {
    id: "tc2",
    session_id: "demo-session",
    content: "Interesting.",
    sent_at_ms: 120000,
    sent_at: new Date().toISOString(),
  },
  {
    id: "tc3",
    session_id: "demo-session",
    content: "You might like this next.",
    sent_at_ms: 210000,
    sent_at: new Date().toISOString(),
  },
  {
    id: "tc4",
    session_id: "demo-session",
    content: "What if we tried something different?",
    sent_at_ms: 340000,
    sent_at: new Date().toISOString(),
  },
  {
    id: "tc5",
    session_id: "demo-session",
    content: "You keep coming back to this.",
    sent_at_ms: 520000,
    sent_at: new Date().toISOString(),
  },
  {
    id: "tc6",
    session_id: "demo-session",
    content: "Almost there. One more.",
    sent_at_ms: 700000,
    sent_at: new Date().toISOString(),
  },
];
